### ISSUE TITLE
Forgotten password

### ISSUE THREAD

**Issue by normanmasia** [treeDiM/StackBuilder#100]
The button "Forgotten Password" doesn't work.
I've tryed adding the mail, and click on "Forgotten Password" but nothing happens.
Thanks,
norman

**Comment by normanmasia** [comment]
I'm still in version 3.0.0.35 with the password forgotten.
Is possible to reset it ?¿
I've tryed in http://plmpack.azurewebsites.net/Account/ForgotPassword but any mail received.
TIA

**Comment by fgasnier71** [comment]
Did you check your SPAM folder?
Are you sure you entered the same email as initially entered when creating your account?

Please, if the above does not help please give me your email and I will try to reset your password with a given one. Using the website,  you should then be able to change it.

**Comment by normanmasia** [comment]
Yes, I've checked my Spam folder and yes, when I try to re-open an account with my mail the system says that there are already an account with my mail.
My mail is nmasia@hinojosa.es
Many thanks,
