### ISSUE TITLE
Case Analysis using multiple box sizes

### ISSUE THREAD

**Issue by barca91chen** [treeDiM/StackBuilder#102]
Currently, the stackbuilder software allows for packing optimzation for 1 single box size when packing into a case. However there are cases where different box sizes are packed into a case. Please help me to understand what are the steps needed to execute this analysis. Thank you very much.

**Comment by fgasnier71** [comment]
The current version of StackBuilder does not allow to handle multiple box sizes.
Future versions of StackBuilder might allow heterogeneous stacking.
