### ISSUE TITLE
bug: lorsque l'on essai de quitter une fenêtre elle réapparait

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#103]
Lorsque l'on ferme la fenetre "caisse" ou n'importe quelle autre, elle se ré-ouvre. Il fautl a fermer 3 fois pour quelle parte
![image](https://user-images.githubusercontent.com/5374935/29518959-c9718ff4-867b-11e7-8613-b3253c0d6b84.png)

**Comment by fgasnier71** [comment]
Impossible de reproduire ce bug.
@pbuffet : Le problème est-il corrigé de ton côté?
