### ISSUE TITLE
edition d'analyse

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#104]
permettre d'éditer l'analyse en double cliquant sur sont icone dans l'arborescence. Comme pour les autre éléements.

**Comment by fgasnier71** [comment]
Ce n'est pas souhaitable car l'utilisateur pourraît perdre la configuration de la palette qu'il a défini précédemment. Il dispose toujours de l'item "Editer..." du menu contextuel pour editer l'analyse.
