### ISSUE TITLE
Bug Solutions pour (2 x LongCais) +LargCais > LargPalet

### ISSUE THREAD

**Issue by anobre** [treeDiM/StackBuilder#112]
Pas de solutions proposées pour certaines combinaisons de valeurs:
par exemple : caisse = 413 x 313 x h , palette = 1200 x 1000

Pas de solutions proposée avec erreur suivante :

432188 [1] ERROR treeDiM.StackBuilder.Desktop.FormNewAnalysisCasePallet – treeDiM.StackBuilder.Engine.EngineException: Pattern name=Interlocked Filled : actualLength=1139 > palletLength=1000 ?

or 11339 = 2 x 413 + 313

**Comment by fgasnier71** [comment]
* Exception is being caught which allows the computation to continue.
