### ISSUE TITLE
Définir une BDD des solutions palette commune à plusieurs utilisateurs

### ISSUE THREAD

**Issue by fdicresc** [treeDiM/StackBuilder#114]
Bonjour,

Je cherche à savoir comment faire pour partager entre plusieurs utilisateurs la BDD de solution palette.
En effet, je partage sur un disque réseau un même fichier projet, mais il semble que la BDD soit propre à chaque poste.
Y a t'il un moyen de localiser une BDD au même endroit pour tous les utilisateurs utilisant des ordinateurs différents ?

Merci pour vos réponses

**Comment by fgasnier71** [comment]
Bonjour,
Quelle version utilisez-vous?
Si vous utilisez la version 3.0, la base de donnée des différents composants est dans le Cloud (MS Azure) et est accessible par tout les comptes appartenant à un même groupe.
Cependant, il est nécessaire d'utiliser le logiciel PLMPack Lib pour créer un nouveau groupe et y adjoindre tous les compte d'un même groupe. Enfin, tous les utilisateurs doivent définir ce groupe comme leur groupe courant.
Cordialement,

**Comment by fdicresc** [comment]
Bonsoir,

Je suis effectivement sur la 3.0. 
Merci pour la réponse.
J'ai testé et ca fonctionne.
Cordialement
