### ISSUE TITLE
Pas de sauvegarde des cornières, coiffe, film palettisation dans les analyses

### ISSUE THREAD

**Issue by fdicresc** [treeDiM/StackBuilder#118]
Bonjour,

Lorsque l'on fait une analyse pour un plan de paletisation, le système ne sauvegarde pas les choix que l'on fait pour les cornières, coiffe et film.
Il faut à chaque nouvelle ouverture de l'analyse, recocher les choix.

Merci de votre aide
Cordialement
Frédéric

**Comment by fgasnier71** [comment]
Problem solved in version 3.0.0.51.

**Comment by fdicresc** [comment]
Thanks !
