### ISSUE TITLE
Perte des images des faces

### ISSUE THREAD

**Issue by ArnaudSB** [treeDiM/StackBuilder#119]
Bonjour,
Je rencontre un problème avec la version 3.0.0.53,
Il m'est parfaitement possible d'appliquer des images sur les faces de mes étuis ou cartons (une étiquette Recto et une étiquette verso par exemple), il m'est ensuite possible de visualiser les cartons ou palettes pleines avec les images/etiquettes.
Mais, j'ai beau "enregistrer" : à la réouverture du projet (_si je ferme SBuilder et si je le réouvre puis que je réouvre le fichier dans lequel je viens de régler les images sur mes produits_) il arrive très fréquemment (presque tout le temps) que les images aient complètement disparues..
Il faut alors reconfigurer toutes les images avec la perte de temps associée.

Avez vous déjà rencontré cette problématique ?

Merci, Sincères Salutations

**Comment by fgasnier71** [comment]
Je n'arrive pas à reproduire ce bug.
* Constatiez-vous ce bug sur les versions précédentes?
* Pouvez-vous me faire parvenir un fichier zip contenant un fichier stb dans lequel les textures ont disparus?
* Si vous ouvrez dans bloc note (notepad.exe) le fichier stb sauvegardé, y trouvez-vous un élément "Textures"?
Cordialement,

**Comment by ArnaudSB** [comment]
*Suite bug de taille, **Nouvel envoi avec Wee transfer.*

*https://we.tl/vZnDko6gsF <https://we.tl/vZnDko6gsF> *

*Suite bug de taille, Nouvel envoi avec les pièces jointes zippées.*

Bonjour,
Oui il m'arrivait d'avoir le bug dans des versions précédentes mais je
recommençais une fois et c'était réglé (mes données n'étaient plus
perdues). Là c'est systématique, je n'arrive pas à enregistrer de manière
pérenne les labels sur les faces.
Je me suis dit que le logiciel n'aimait pas que j'utilise les mêmes images
plusieurs fois, j'ai donc dupliquer les fichiers images pour n'utiliser
chaque fichier qu'une seule fois - Pas d'amélioration.
Je me suis dit que le logiciel v3 travaillait avec un fichier créé par la
v2. J'ai donc intégralement recréé les données depuis la v3 (les étuis,
cartons, palette et les labels associés) - Pas d'amélioration (= tout
fonctionne mais lorsque je ferme le fichier et que je le ré-ouvre le
lendemain pour poursuivre mon travail, il n'y a plus de label sur les étuis
ou cartons)
Je me suis dit que la nouvelle solution de stockage cloud des objets allait
m'aider, j'ai transféré des objets sur votre cloud mais même problème. A la
réouverture j'ai perdu les labels.

Voici en pièce jointe un stb (le v3.1, créé avec la v3 de StackB) où vous
trouverez par exemple l'étuis de 10l et le carton de 2x10l avec les
étiquettes... et le carton de 12x1 l sans étiquette alors que je passe mon
temps à les mettre.
Le v2 également en pièce jointe est le fichier initialement créé sous la v2
de StackB et travaillé également sous la v3 de StackB : et il présente le
même problème. Normalement tous les étuis et cartons ou au moins 1
étiquette et jusqu'à 4.

Troisième fichier en pièce jointe : un rapport correspondant au produit 1l
qui montre bien que lorsque j'avais bien renseigné tous les labels avant de
les perdre à la réouverture du fichier.


Avec Notepad, si j'ouvre le v3.1 je retrouve bien un champs texture et des
infos pour le produit 10l et le carton 2x10l qui fonctionne bien. Et le
produit 12x1l présente lui aussi un champ Facetexture et des infos alors
qu'il bug.


Faut-il respecter un poids max pour les images ? Je peux travailler à
alléger au max les visuels.

Merci pour votre retour.
Bien à vous,
Arnaud Leclère

Le 15 novembre 2017 à 23:30, François Gasnier <notifications@github.com> a
écrit :

> Je n'arrive pas à reproduire ce bug.
>
>    - Constatiez-vous ce bug sur les versions précédentes?
>    - Pouvez-vous me faire parvenir un fichier zip contenant un fichier
>    stb dans lequel les textures ont disparus?
>    - Si vous ouvrez dans bloc note (notepad.exe) le fichier stb
>    sauvegardé, y trouvez-vous un élément "Textures"?
>    Cordialement,
>
>
Le 17 novembre 2017 à 12:08, Arnaud LECLÈRE <leclere.arnaud@gmail.com> a
écrit :

**Comment by fgasnier71** [comment]
Ai trouvé l'origine du bug. La position des textures est mal enregistré dans le fichier parce qu'avec les settings de l'OS en Français des '.' sont remplacés par ','.
Le bug sera corrigé dans la version 3.0.0.54.
En attendant vous pouvez éditez vos fichiers manuellement pour les récupérer.
Avec notepad, ouvrir le fichier .stb et dans l'élément FaceTexture / attributs Position+Size remplacer 1 ',' par '.'.
Par exemple:
` <FaceTexture FaceNormal="YP" Position="(11,15, 7)" Size="(27,5, 15,5)"... />`
devient:
`<FaceTexture FaceNormal="YP" Position="(11.15, 7)" Size="(27.5, 15.5)"... />`

Ce n'est donc pas dû à la taille des images.

Pour aider à trouver le problème, on peut activer Options>Débogage>Afficher la console de Logging...
Merci pour vos efforts.

**Comment by ArnaudSB** [comment]
C'est moi, Merci parfait.
A plus tard.
Arnaud

Le 17 novembre 2017 à 17:14, François Gasnier <notifications@github.com> a
écrit :
