### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by YannickClevy** [treeDiM/StackBuilder#125]
Hi,

following the instructions on a fresh win2012R2 virtual machine fully updated.

.Net framework 4.7.2
IIS 8.59.600.16384
Web Deploy 3.6

The package CMD returns following message:

_Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. Tous droits r‚serv‚s.

PS C:\Users\administrateur.BDMB> cd C:\_install\treeDiM.StackBuilder.Installer_toBeExtracted
PS C:\_install\treeDiM.StackBuilder.Installer_toBeExtracted> .\treeDiM.StackBuilder.WCFAppServ.deploy.cmd /Y
SetParameters from:
"C:\_install\treeDiM.StackBuilder.Installer_toBeExtracted\treeDiM.StackBuilder.WCFAppServ.SetParameters.xml"
You can change IIS Application Name, Physical path, connectionString
or other deploy parameters in the above file.
-------------------------------------------------------
 Start executing msdeploy.exe
-------------------------------------------------------
 "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:package='C:\_install\treeDiM.StackBuilder.Installer
_toBeExtracted\treeDiM.StackBuilder.WCFAppServ.zip' -dest:auto,includeAcls="False" -verb:sync -disableLink:AppPoolExtens
ion -disableLink:ContentExtension -disableLink:CertificateExtension -setParamFile:"C:\_install\treeDiM.StackBuilder.Inst
aller_toBeExtracted\treeDiM.StackBuilder.WCFAppServ.SetParameters.xml"
InfoÂ : Ajout de sitemanifest (sitemanifest).
InfoÂ : CrÃ©ation de lâ€™application (StackBuilderWCFAppServ)
InfoÂ : Ajout du chemin dâ€™accÃ¨s virtuel (StackBuilderWCFAppServ)
Code d'erreurÂ : ERROR_SITE_DOES_NOT_EXIST
Informations supplÃ©mentairesÂ : Le site 'StackBuilderWCFAppServ' n'existe pas.  Pour en savoir plusÂ : http://go.micros
oft.com/fwlink/?LinkId=221672#ERROR_SITE_DOES_NOT_EXIST.
Nombre d'erreursÂ : 1.
PS C:\_install\treeDiM.StackBuilder.Installer_toBeExtracted>_

I tried iisreset, reboot several times, admin powershell console....

Is there a manual way to install the APP ?

Regards, Yannick

**Comment by normanmasia** [comment]
Hi,
I've had exactly the same problem.
In a new installation on a Azure machine.
Following all the steps correctly until to run the CMD and have had the same final instruction:
ERROS_SITE_DOES_NOT_EXIST.

Enclosed a Capture Screen:

![capture](https://user-images.githubusercontent.com/24763543/42817803-81796da4-89cf-11e8-8e9d-5f4705a30b99.JPG)

**Comment by YannickClevy** [comment]
Good to know that I'm not alone !

**Comment by fgasnier71** [comment]
I updated the packages and manual with ones that are known to work with at least 2 different customers.
Is your win2012R2 virtual machine reachable online?
A manual way to install: You could compile the WCF service with VS2017 CE and install the resulting libraries in a IIS website folder.

**Comment by YannickClevy** [comment]
Hi,

I'm very sorry but this fix didn't work.

Still the same messages.

Yannick

**Comment by YannickClevy** [comment]
fyi manual was not updated and the package was renamed in between.

**Comment by normanmasia** [comment]
Hi,
Exactly the same for me, with the same error.

**Comment by fgasnier71** [comment]
It seems that, for a successful deployment, one has to create the website StackBuilderWCFAppServ manually in IIS...
I am adding this to document "How to deploy WCF StackBuilder Service.pdf"

**Comment by normanmasia** [comment]
Enclosed a couple of captures
![capture1](https://user-images.githubusercontent.com/24763543/44514354-2638fa00-a6c0-11e8-8d7d-0a631a65ef93.JPG)
![capture2](https://user-images.githubusercontent.com/24763543/44514355-2638fa00-a6c0-11e8-8ded-b4f0fa3fa3bb.JPG)
