### ISSUE TITLE
Ability to disable cloud services

### ISSUE THREAD

**Issue by Alko89** [treeDiM/StackBuilder#127]
I have been playing around with StackBuilder and was unable to open the app due to unavailable cloud service (plmpackcloudservice.cloudapp.net).
Is there a way to disable web services to be able to use the app offline?

**Comment by fgasnier71** [comment]
The web service is available now and 99...% of the time. Your firewall might well be responsible for preventing access to the web service.
Once you have created an account and logged in, you can go to settings and check Options>Debugging>Allow disconnected usage...

**Comment by Alko89** [comment]
Thanks a lot for the help, I noticed it started working as soon as I opened the ticket.
I also noticed the graphics are not shown when creating a new box or case in the latest master. Are you avare of that or should I open a new ticket?

**Comment by fgasnier71** [comment]
Are you using another language than English?
This might come from ill-translated resources.

**Comment by Alko89** [comment]
I added some Slovenian translations. I tried changing to English and have the same issue.

**Comment by Alko89** [comment]
I'm working with the source code from master branch :)
