### ISSUE TITLE
Document Explorer missing and keeps making me log into stackbuilder

### ISSUE THREAD

**Issue by KHMPlastics** [treeDiM/StackBuilder#128]
so stack builder has been like this for a little while now the only reason i waited was to see if there was an update to fix the problem but alas its not getting fixed on my end when i first downloaded this software it worked great and everything showed up about 2 months ago it started doing errors all the time saying I'm not signed in it wont accept my username but will allow me to use the software if i use any email address in the username field, but my main problem is i don't see the document explorer and its really annoying that i cant confirm or edit carton or skid i just made on the side panel like its suppose to be can anyone give me a helping hand please
![untitled](https://user-images.githubusercontent.com/46382001/50708984-df72ed80-102b-11e9-8bcc-222f5f133fb9.png)
Update 1/9/19
found this poking around I did let the treeDim.StackBuilder.Desktop.exe file through but not sure what to do about the website 
![untitled2](https://user-images.githubusercontent.com/46382001/50904693-984b7a80-13e6-11e9-8b65-9e0326ca412c.png)

**Comment by fgasnier71** [comment]
Did you try uninstalling / resinstalling?
Regards,

**Comment by KHMPlastics** [comment]
nope didn't work got the debugger on and see this popping up when i go to Help - About

100209 [1] ERROR treeDiM.PLMPack.DBClient.WCFClient – System.ServiceModel.FaultException: An error occurred when verifying security for the message. 
106084 [1] ERROR treeDiM.PLMPack.DBClient.WCFClient – Communication exception in WCFClient.Dispose() : The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state. 
106084 [1] ERROR treeDiM.StackBuilder.Desktop.AboutBox – The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

**Comment by fgasnier71** [comment]
Is the problem fixed with the latest version?
If not, please, reopen the issue.

**Comment by KHMPlastics** [comment]
It works on any other computer that isn’t running trend micro its something to do with the firewall which I have no control over unfortunately so I don’t think it will get fixed unless we have our techs look into it

**Comment by fgasnier71** [comment]
Thanks for taking the time to answer this.
