### ISSUE TITLE
Cylindrical products

### ISSUE THREAD

**Issue by Omisanfarmaceutici** [treeDiM/StackBuilder#129]
it is possibile to create a cylindrical product or only squared products?
It would be nice since most of the products for which I have to design the palletization are cylindrical.
Thanks,

**Comment by fgasnier71** [comment]
If your using version 3.0, there is an option for cylindrical palletization.
![image](https://user-images.githubusercontent.com/1512039/52143092-e73da600-265a-11e9-8091-78782c9174bd.png)
