### ISSUE TITLE
export complet

### ISSUE THREAD

**Issue by guillaume3572** [treeDiM/StackBuilder#130]
Bonjour,
il y a t'il moyen d'obtenir un export de tout les éléments constituant la palette : je n'ai pas la présence des intercalaires dans le fichier XML de sortie (après l'analyse) ?
J'ai donc modifié le ReportTemplateHtml.xsl pour afficher TOUT le XML, mais je me rends compte que cette fois ci, je n'ai pas accès aux positions des différents objets constituant la palette !
Merci de me dire si il est possible d'obtenir un fichier avec l'ensemble de ces informations.
Bien cordialement,

**Comment by fgasnier71** [comment]
Parle-t-on bien du rapport dans le cas d'une analyse homogène caisse/palette?
Selon moi, tout fonctionne normalement.

**Comment by guillaume3572** [comment]
Oui, dans le rapport (personnalisable via xslt) il manque les éléments suivants : 
-localisation x,y,z et angle des colis
-localisation des intercalaires (sur la couche 2 ou 3 par exemple) -> nous avons juste la quantité d’intercalaire présent

Sur le fichier xml ou csv (export direct) : 
pas de notion d'intercalaires (présence/absence/position)

**Comment by olivluca** [comment]
Hello, (sorry I don't speak/write french but I understand some of it).
I have the same problem. 
The only way to see the interlayer is to use the "csv (TechnologyBSA)" format (a format which, instinctively, I don't like).
Would it be possible to add the interlayers in the xml export file?

**Comment by fgasnier71** [comment]
Would you become a Premium (50€) user to get it?
Regards,

**Comment by olivluca** [comment]
I'll have to ask my boss

**Comment by olivluca** [comment]
Wait, it's a "feature" only for premium users or you need to be premium to have the bug (if it is a bug) fixed?

**Comment by fgasnier71** [comment]
Not a "feature" for Premium users. You can call it a bug if you like. 
If you need it to be fixed by tomorrow, and that I stop working on what I am currently doing, I had rather doing it for someone that supports the project.

**Comment by olivluca** [comment]
I understand and I agree. I'll pass the issue to my boss. Thank you.

**Comment by olivluca** [comment]
I hope you received the payment (m_sist at wetron dot es), I don't need it to be fixed by tomorrow, next week is fine (just kidding :grin:).
Now, seriously, I need to know what format you're going to use so I can write my parser. I guess you'll have to add a new \<item\> to specify the interlayer data and add  a \<placement\> for each interlayer in the correct sequence (i.e. after the last box of the layer), but you'll decide what's best.
I do need the dimensions and the final position of the interlayer because I'm going to use the xml file to drive a robot.

**Comment by fgasnier71** [comment]
Thanks. I will inform you when I am done.

**Comment by fgasnier71** [comment]
Interlayers now added in csv export...

**Comment by olivluca** [comment]
Thank you, are you going to push a release or do I have to setup a build environment to build it?

**Comment by fgasnier71** [comment]
Would you like to receive a temporary setup? I will publish a new version only in a few days.

**Comment by olivluca** [comment]
I can wait, thank you.

**Comment by olivluca** [comment]
I just tried the new release 3.0.2.26 and I'm afraid the xml export is broken: now the _placement_ items are missing the rotation fields **L** and **W**. 
Also, in the _statistics_ section loadWeight has been changed to weightLoad (but that's easy to fix in my parser).

**Comment by fgasnier71** [comment]
@olivluca : Please download version 3.0.2.27.

**Comment by olivluca** [comment]
Wow, that was fast, thank you.
