### ISSUE TITLE
suggestion: ControlTipText “Edit pallet solution database...” 

### ISSUE THREAD

**Issue by ed152** [treeDiM/StackBuilder#133]
Hello,
My suggestion:
I think ControlTipText “Edit pallet solution database...” should be the same name as the dialog title: “Edit database & import items in project…”
PLMPack StackBuilder, Version 3.0.1.0
Yours sincerely
Eduard
![grafik](https://user-images.githubusercontent.com/49289818/63980519-29797980-cabc-11e9-88f6-c2742f2b39c5.png)
![grafik](https://user-images.githubusercontent.com/49289818/63980524-31391e00-cabc-11e9-8950-cd9b84fb5e6d.png)

**Comment by fgasnier71** [comment]
Done!
