### ISSUE TITLE
suggestion: term "project" instead of "document"

### ISSUE THREAD

**Issue by ed152** [treeDiM/StackBuilder#134]
Hello,
to make everything consistent, i suggest to use the term "project" instead of "document" in these places.
![grafik](https://user-images.githubusercontent.com/49289818/63980760-d48a3300-cabc-11e9-9f2f-e0e41af900c0.png)
PLMPack StackBuilder, Version 3.0.1.0
Yours sincerely
Eduard

**Comment by fgasnier71** [comment]
Done!
