### ISSUE TITLE
admissible loads setting is not saved

### ISSUE THREAD

**Issue by rrichardsson** [treeDiM/StackBuilder#143]
the field of admissible load will not save when creating a new pallet. 
![tempsnip](https://user-images.githubusercontent.com/60225386/72994460-c1a23300-3dbc-11ea-98fb-248a5e37f17c.png)

**Comment by fgasnier71** [comment]
https://github.com/treeDiM/StackBuilder/commit/8068cfed4eae281bff43f2c5764ebbc9d83033b5#diff-28d866cdad97f563044d16bce1d1e6ba #
