### ISSUE TITLE
New Pallet Options:

### ISSUE THREAD

**Issue by AndrewF74** [treeDiM/StackBuilder#145]
Is there a way to get new pallet options loaded? I am looking for:
"48” x 40” GMA grade A pallet with four-way forklift entry"
It would look something like this:
![image](https://user-images.githubusercontent.com/60245283/73038388-7d8c4e00-3e0f-11ea-9266-be45a0a724d3.png)

Also, I am looking for a way to also add a texture to the pallet.

**Comment by fgasnier71** [comment]
* Added an approximated GMA 48*40 with 4-way forklift entry,
* In the future, a feature to load tesselated solid pallets might be added.
