### ISSUE TITLE
Tubes?

### ISSUE THREAD

**Issue by AndrewF74** [treeDiM/StackBuilder#148]
Is there a plan/need for others to have tubes added to the StackBuilder program?

Example:
 
![image](https://user-images.githubusercontent.com/60245283/73038953-82520180-3e11-11ea-9742-9b5d49e4ec81.png)

**Comment by fgasnier71** [comment]
No one requested for those before.
Really wonder how they stack as they rarely come alone (either in boxes or in plastic clamshells).
