### ISSUE TITLE
ECT Edge Crush Test

### ISSUE THREAD

**Issue by AndrewF74** [treeDiM/StackBuilder#149]
Is there a way to have a limitation on a case that prevents too many layers to be placed on it? I know there is a restriction of how much weight to put into the box, but what about on top of the case when configuring the palletization analysis? There is such a thing as too high for a weak case.

Example:
If you have a case that has a weight restriction of no more than 40 lbs. but you put additional layers of cases on top of that case. At some point, the bottom case will begin to bow and will eventually crush.

**Comment by fgasnier71** [comment]
As I understand it the ECT module already does that.
![image](https://user-images.githubusercontent.com/1512039/73136901-1bbc2600-4053-11ea-9487-8b1135c3e4b7.png)
