### ISSUE TITLE
Generate StackBuilder Project from PackLib Box/Case/Pallet optimisation

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#15]
Add button to generate StackBuilder Project from PackLib Box/Case/Pallet optimisation

![sans titre](https://cloud.githubusercontent.com/assets/5374935/3427591/ab43da9e-0034-11e4-80d7-f22a39ee24a2.png)

Before you use the "optimise", button are grey (not available)

**Comment by fgasnier71** [comment]
* Cf PLMPackLib.
* A priori, c'est terminé. Je ferme. 
@pbuffet : Tu peux réouvrir si nécessaire.
