### ISSUE TITLE
Pallet/truck analysis is empty

### ISSUE THREAD

**Issue by romeograhameco** [treeDiM/StackBuilder#151]
Using Versions 3.0.2.7 on Windows 10.

When I try to create a truck load with a pallet, the analysis shows layers, but then when I click Next, the analysis shows the empty truck, and no pallets loaded.

Also, I don't know how to get 2 layers of pallets to show.

Thanks!
romeo

**Comment by fgasnier71** [comment]
Please check Truck maximal loading weight...
It is probably set to zero.

**Comment by romeograhameco** [comment]
Yes - that was it!  Thanks for the help.
