### ISSUE TITLE
Missing the auto Highlight/Select feature

### ISSUE THREAD

**Issue by Eskilader** [treeDiM/StackBuilder#154]
Hi!

Excellent software that I use almost everyday! But I think it can be even better with this small but important function.
When you for example input dimensions in the software by clicking with your mouse in a box I miss the function that highlights or selects the number thats already in the box. When using TAB to move to the next box is getting quite tedious when you have to start by deleting the numbers thats already in the box.

Small and simple improvement yet this will help a bunch!

Thanks!

**Comment by fgasnier71** [comment]
Done!
