### ISSUE TITLE
More than case analysis (mixed case)

### ISSUE THREAD

**Issue by Xetanor** [treeDiM/StackBuilder#169]
hi

Can I analyze pallet placement for more than one case?

i mean mixed case..

thanks..

**Comment by Xetanor** [comment]
I mean, can I add more than one cover to a palette?

**Comment by ed152** [comment]
Do you mean this?
![Screenshot 2021-05-28 151015](https://user-images.githubusercontent.com/49289818/119989158-254afa80-bfc7-11eb-982d-c0d8b022e500.png)

**Comment by fgasnier71** [comment]
Thank you @ed152 for answering.
@Xetanor you might see that the algorithms available are rather poor. I will work on improving them but if you need better results quickly you might have to consider other software packages.
