### ISSUE TITLE
Heterogeneous Truck / Pallet Generation Not Functioning

### ISSUE THREAD

**Issue by title1pro** [treeDiM/StackBuilder#171]
Since a recent update Heterogeneous Truck and Pallet Generation are no longer functioning. They do not show a preview of the pallet and the "next" button is not functional.

**Comment by fgasnier71** [comment]
Would you tell me which version?

**Comment by lacroix999** [comment]
I believe it's Version 3.0.2.38. I am facing the same issue.

**Comment by lacroix999** [comment]
![image](https://user-images.githubusercontent.com/91861848/135788638-aa9b683a-2146-4368-a9b8-c2ee1d25a4b9.png)

here's a screenshot for references.

**Comment by fgasnier71** [comment]
I can not reproduce this bug.
Can you send the file *.stb file that you are using at fgasnier_at_treedim_dot_com?
