### ISSUE TITLE
Boxes & Anaylisys project explorer sorting

### ISSUE THREAD

**Issue by rohaochao** [treeDiM/StackBuilder#175]
I am having trouble with how to sort the items in project explorer. As I am adding more boxes and creating more analysis, it makes a lot of sense to have the items sorted to increase browsing speed. Is there a  method to sort the items in StackBuilder?

OS: Windows 10
StackBuilder Ver: 3.0.2.55

**Comment by fgasnier71** [comment]
Push your items (cases, pallets...) into the database.
Then create a different file for each project.
