### ISSUE TITLE
Box barcode outwards stacking type？

### ISSUE THREAD

**Issue by ziqinchao** [treeDiM/StackBuilder#177]
One side always faces out

**Comment by ziqinchao** [comment]
<img width="95" alt="1028" src="https://user-images.githubusercontent.com/18421512/198541464-a96c042a-700f-473b-ba69-2866f5958cca.png">
As shown in the figure, the small green dot is the two-dimensional code, which ensures that the two-dimensional code of all the boxes generated by the stacking type is on the outside

**Comment by fgasnier71** [comment]
![image](https://user-images.githubusercontent.com/1512039/199109913-3e909963-af63-4050-be5a-43382c91c6fe.png)

I believe you can make sure that a facing is pointing outside of the pallet.

**Comment by fgasnier71** [comment]
If you think this is not a valid answer, please reopen this issue.
