### ISSUE TITLE
TEST StackBuilder V2.0.0.0 

### ISSUE THREAD

**Issue by anobre** [treeDiM/StackBuilder#26]
Cornières : 
    1)  lorsque l'on assigne une cornière à une analyse il faudrait que les valeurs de débord X et Y soit automatiquement réduite de 2x la valeur de l'épaisseur de la cornière. Cela permet d'avoir par défaut des cornières à l'intérieur de la palette. L'utilisateur peut ensuite modifier ces valeurs. 
     2) couleur par défaut : vert kaki

Coiffe :
     1) lorsque l'on assigne une coiffe à une analyse il ne faut pas empêcher de mettre la coiffe avant le calcul. Il faut, une fois le calcul de la palettisation terminée, vérifier si la coiffe est "supérieure" aux dimensions de la couche. Si elle est inférieure, afficher un message "impossible"
     2) couleur par défaut : vert kaki

Film :
     1) ne fonctionne pas avec l'install v2.0.0.0 : plante directement --> il doit manquer une ressource à l'install.

**Comment by fgasnier71** [comment]
Le point Coiffe 1) me paraît une très mauvaise idéé: comment afficher un message impossible sur une solution qui ne peut exister.
Je n'ai jamais vu de code de calcul qui commence un calcul alors que les conditions aux limites sont contradictoires ou que le modèle est surconstraint.
Peut-être pourrait-on empêcher de définir les débords lorsqu'il y a une coiffe comme je l'avais proposé initialement.
Comment fonctionnent PUZZLE ou CAPEPACK?
