### ISSUE TITLE
Icon Add new Film

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#28]
![film](https://cloud.githubusercontent.com/assets/5374935/5958010/9d371388-a7c0-11e4-939b-a4120ef3bb0b.png)

**Comment by fgasnier71** [comment]
Il faut aussi l'icône en 16*16...

**Comment by pbuffet** [comment]
![film16](https://cloud.githubusercontent.com/assets/5374935/5958376/2f840ce8-a7c4-11e4-8c98-f765ee188504.png)
