### ISSUE TITLE
Allow user to load more layer patterns or modify existing layer patterns

### ISSUE THREAD

**Issue by fjpereza** [treeDiM/StackBuilder#31]
would be nice if I could load layer patterns or modify existing layer patterns.

**Comment by fgasnier71** [comment]
A pattern is actually an algorithm and can not be easily described.
Can you give some details/samples (ideally drawings) about the layer pattern you might need and how you would like to modify an existing layer patten?
Is this feature available on any other palletisation software?

**Comment by fjpereza** [comment]
I thought so. I need this layer pattern, but it doesn't appear in box/pallet analysis.

![20150326 layer pattern](https://cloud.githubusercontent.com/assets/937575/6843162/06f34ed8-d398-11e4-90af-aebcbd35fbdd.png)

Thanks for your reply.

**Comment by fgasnier71** [comment]
It looks like this solution does not give better result in term of efficiency than a column layout.
Can give case + pallet dimension or send .stb file at fgasnier71_at_gmail_dot_com (replace _at_ and _dot_)?

**Comment by fjpereza** [comment]
I've sent you an email.

**Comment by fgasnier71** [comment]
I am not sure I can understand what you mean.

You need the pattern shown above (that actually appear as index 50 in your case/pallet analysis) to be also available in box/case analysis. Is that right?

If so, I can tell you that it does not appear in your box/case analysis only because of different conditions (e.g. box does not seem to be have length = 2*width as case in pallet analysis)

Regards,

**Comment by fjpereza** [comment]
The index 50 is
![20150326 index 50](https://cloud.githubusercontent.com/assets/937575/6880540/edb894da-d52e-11e4-80e4-416de89619e0.png)

But I need this layer pattern
![20150326 layer pattern](https://cloud.githubusercontent.com/assets/937575/6880543/faf96066-d52e-11e4-9e4a-ef3c8b27805d.png)

**Comment by fgasnier71** [comment]
Thanks, you found a bug.
I failed to notice that layer 1 and 2 are actually the same which makes no sense.
This should be corrected when I build the new version.
Regards,

**Comment by fjpereza** [comment]
Thank YOU!

**Comment by fgasnier71** [comment]
Premium users can now edit their layers.
