### ISSUE TITLE
Excel libary

### ISSUE THREAD

**Issue by xHuubx** [treeDiM/StackBuilder#38]
Would it be possible to also add bundles and packs to the the excel Excel libary?

**Comment by fgasnier71** [comment]
Thanks for your input.
Adding bundles could be done. On the other hand, packs are difficult to implement as they have to refer to a box that is supposed to be in an other tab of the sheet.

Anyway, we are currently working on an online database (hosted on MS Azure) which will allow storing all your items (pack included) and in the end, the only purpose of the Excel file loader might be to fill the user database.
