### ISSUE TITLE
Can't use pallet database

### ISSUE THREAD

**Issue by xHuubx** [treeDiM/StackBuilder#42]
I Installed version 2.0.23.0 on a other PC, and after installing I transferred my "PalletSolutionsDB" folder to the new PC in the Stackbuilder folder. Before transferring I renamed the one that is installed standardly. When I now open the SB and go to Tools >> Edit pallet solution database.. I get a window saying "Pallet solution database is empty. Closing form.." I am sure the folder contains all the database solutions I want to use. Is there a other way to transfer the PalletSolutionsDB to a new install or other PC ?

**Comment by fgasnier71** [comment]
I seem to be able to reproduce the bug. I will keep you updated when it is corrected.
Thanks for warning us. Regards,

**Comment by fgasnier71** [comment]
Can you make sure you also copied a file named **index.xml** together with stb file of the database?
Its full path ought to be:
'C:\Program Files (x86)\treeDiM\PLMPack\StackBuilder\PalletSolutionsDB\index.xml'

If it still does not work, could you please send a zip archive of your database directory at the following email adress: fgasnier_at_treedim_dot_com.
Regards,

**Comment by xHuubx** [comment]
You are right, including index.html fixed the problem, THX!!
