### ISSUE TITLE
"Lastest release"  lien de téléchargement

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#43]
"Lastest release"  est maintenant utilisé comme lien pour obtenir la dernière version de StackBuilder.
est il possible d'attribuer cette étiquette qu'aux versionx contenant un .exe?

Est ce que cela est problématique?

Est il possible de créer une autre étiquette dédié au téléchargement de la version?

**Comment by pbuffet** [comment]
Pour résoudre plus facilement, le lien se fera vers codeplex

**Comment by fgasnier71** [comment]
Attention! Stackbuilder va disparaître de la plateforme Codeplex qui est condamnée.
