### ISSUE TITLE
StackBuilder Open - activation

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#44]
changer le système d’activation:
Le système actuel n'est pas très intuitif est des utilisateurs bloquent à cette étape.

Proposition 1 :

même systeme mais l'envoi du mail de requête se fait depuis la fenêtre d'installation.
(ouverture de l'application mail par défaut) 

![image](https://cloud.githubusercontent.com/assets/5374935/12619865/3e406da2-c51a-11e5-95f1-743867a98e84.png)

Proposition 2 : 

Pas de numéro de série à l'installation, mais au bout de quelques jours l'application demande de remplir un formulaire de contact, pour recevoir le numéro de série  (envoi sur softkey@treedim.com)

Le but de l'activation est de récupérer les coordonnées des utilisateurs, sans les bloquer lors de l'installation.

La discutions est ouverte, qu'est ce que vous en pensez?

**Comment by fgasnier71** [comment]
idéalement, lier le fonctionnement avec la plateforme PLMPack sous Azure.
--> Le lancement de l'application et l'utilisation de la base de donnée en
ligne nécessite de s'enregistrer sur la plateforme PLMPack.

------------------------------------------------------------
François GASNIER
20, rue Hechner
67000 STRASBOURG
Tél.: 09 50 04 13 60
http://www.picador.fr
------------------------------------------------------------

2016-01-27 17:28 GMT+01:00 Paul Buffet <notifications@github.com>:

**Comment by fgasnier71** [comment]
Solved with version 3.0.
