### ISSUE TITLE
Page d'accueil web

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#46]
Quelle est l'url de la page d'accueil de stackbuilder?
Est-ce que l'url change en fonction de la langue du logiciel? Si non, est-ce possible?

**Comment by fgasnier71** [comment]
Si "System.Globalization.CultureInfo.CurrentCulture.ThreeLetterWindowsLanguageName" retourne FRA
alors l'URL vaut "http://www.plmpack.com/stackbuilder/stackbuilder_start_page_FRA.htm"
sinon http://www.plmpack.com/stackbuilder/stackbuilder_start_page_ENU.htm

Normalement, on donne une URL fixe mais la page est capable de redirection en fonction de la langue indiquée par le browser.
