### ISSUE TITLE
C# config to compile ?

### ISSUE THREAD

**Issue by snoopy72** [treeDiM/StackBuilder#47]
Hello and thank you for this project, but ...
... i am not able to compile it using VS and/or SharpDevelop.

Where can i find a documentation, which basic prerequisite i need to compile the project on my system ?

> .net V4.5 is installed (also tried with .net V4 without success)
> sharpdevelop 5.1
> wix310 installed via setup

due to the error messages on the compiling, the "signtool.exe" ist missing.

Thanks a lot for all help.

**Comment by fgasnier71** [comment]
Hello,
The project can be compiled with VS2010 or VS2013...
There is no documentation regarding prerequisites.

For all projects, you can remove any execution of signtool in:
Project properties >  Build Events > Post-build event command line
It is only used to sign the software and of course the sign key is not provided in the sources. 
 
Regards,
