### ISSUE TITLE
Guardar en Excel

### ISSUE THREAD

**Issue by forderotekote** [treeDiM/StackBuilder#49]
Buen día!

Tengo una duda, se puede guardar el archivo .stb que genera el software en .xls para poder guardarlos en excel o en .csv.

Saluods

**Comment by fgasnier71** [comment]
.stb file will remain a .xml format file but version 3.0.0.0 of StackBuilder will include a text and csv export of solutions.
Regards,

**Comment by forderotekote** [comment]
Excelente, Muchísimas gracias.
Saludos
