### ISSUE TITLE
Rapport .doc using Libre Office sdk

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#52]
Serait il possible d'utiliser libre office pour générer le rapport en .doc?

http://api.libreoffice.org/ 
http://www.libreoffice.org/download/libreoffice-fresh/?version=5.1.3

**Comment by fgasnier71** [comment]
C'est intéressant. Il semble néanmoins nécessaire d'avoir installé Libre Office pour profiter de l'API!
@pbuffet : Peux-tu expliquer quel est le but recherché par rapport à la méthode existante qui consiste à importer le html généré par l'application dans un document MSWord via automation?

**Comment by pbuffet** [comment]
Notre système actuel ne fonctionne que si Microsoft Word installé sur le poste de l'utilisateur. si il n'achète pas MSWord ils sont bloqué. Libre Office est une alternative intéressante.
De plus notre exporter actuel ne fonctionne plus sous MSWord2015 ( à vérifier @anobre )

Actuellement, Le rapport html ne s'importe pas avec les images dans LibreOffice

**Comment by fgasnier71** [comment]
* New version 3.0.0.36 offers pdf export.
