### ISSUE TITLE
add Strapping on the palettisation

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#53]
Possibilité d'ajouter des cerclages (strapping) sur une palettisation.

nombre de cerclage dans la Longueur L
nombre de cerclage dans la Largeur B
IHM à définir

**Comment by fgasnier71** [comment]
* Non seulement IHM mais aussi comportement du cerclage:
- la forme du cerclage prend-il en compte tous les différents éléments de la palette (ex. interlayer / pallet cap...) ce qui peut manquer de réalisme...
- un nombre 3 cerclages doit-il être impossible parce qu'on ne sait pas ou mettre celui du milieu...

**Comment by pbuffet** [comment]
Les cerclages se répartissent équitablement. 
Lorsque l'on à un nombre de cerclage impair, celui du milieu est légèrement décalé pour ne pas être au niveau du pied de la palette. 
Concernant la forme des cerclages, je propose de ne tenir compte que de l’élément Pallet Cap, pour les autres ça peut passer à travers.

Les cerclages ne sont pas encore une fonctionnalité beaucoup demandé
