### ISSUE TITLE
option overhang length / Width in version  PLM Pack StackBuilder 20.0.30.0

### ISSUE THREAD

**Issue by artesolar** [treeDiM/StackBuilder#63]
Where is the opcion for edit overhang length / Width? i don´t see this opction en palet analisys...  (PLM Pack StackBuilder 20.0.30.0)

Thanks

**Comment by fgasnier71** [comment]
I can see Pallet overhang\underhang on the image below.

![image](https://cloud.githubusercontent.com/assets/1512039/18132222/3c2eae30-6f96-11e6-9ff9-b876f4c80db7.png)

The problem might be related to language used.
Which language are you using?
As a workaround, you can use Settings>Language & Measurement system to switch to english.

**Comment by artesolar** [comment]
i used spanish

Thanks
