### ISSUE TITLE
Rapport Palettisation modifié 

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#65]
[ReportTemplates.zip](https://github.com/treeDiM/StackBuilder/files/511172/ReportTemplates.zip)
- Ajout du nombre de couche dans le détail de la palettisation
- un second modèle de rapport, simplifié pour tenir sur une seule page.
- changement dans les traductions françaises

**Comment by pbuffet** [comment]
Ajout des nouveaux templates par défaut

**Comment by fgasnier71** [comment]
Attention les templates doivent correspondre à la nouvelle version (on n'a plus qu'un type d'analyse) et supporter les analyses imbriquées.
(Je vais vérifier si on peut faire quelque chose avant de décider si je tente d'adapter ou si on ferme)

**Comment by pbuffet** [comment]
Ok, sinon je prépare un nouveau template à partir de celui de la v3

**Comment by fgasnier71** [comment]
Peux-tu envoyer un rapport généré avec le template simplifié histoire de comparer avec la version complète?
Est-ce que cela concernait tous les types d'analyse?

**Comment by pbuffet** [comment]
[Analyse0.zip](https://github.com/treeDiM/StackBuilder/files/987090/Analyse0.zip)
C'est un rapport simplifié tenant sur une seul page, uniquement pour les fonctions de palettisation simple

**Comment by fgasnier71** [comment]
Ai mis en place une forme permettant de définir finement quel paragraphe doit faire partie du rapport.
Je pense que ce rapport simplifié n'a plus lieu d'être.
@pbuffet Si tu penses que ce rapport est toujours nécessaire, réouvre l'issue.
