### ISSUE TITLE
PalletSolutionsDB

### ISSUE THREAD

**Issue by xHuubx** [treeDiM/StackBuilder#68]
I installed the StackBuilder on a new PC, than I renamed the PalletSolutionsDB nae to PalletSolutionsDB_OLD  and I copied my previous PalletSolutionsDB folder, when I now try to access the   solution database I get follwowing error:

"Pallet solution database is Empty"

Any idea how to fix this ?

**Comment by fgasnier71** [comment]
This error occurs because the software failed to load the list of solutions from the file "C:\Program Files (x86)\treeDiM\PLMPack\StackBuilder\PalletSolutionsDB\index.xml"
Can you make sure this file is available?
Regards,

**Comment by xHuubx** [comment]
The index.xml file is available, I have copied the whole PalletSolutionsDB folder..

**Comment by fgasnier71** [comment]
0. Can you check that in application config file "treeDiM.StackBuilder.Desktop.exe.config" that the 
"PalletSolutionsPath" as a value that points to the PalletSolutionDB directory as seen under?

```
<configuration>
...
<applicationSettings>
    <treeDiM.StackBuilder.Desktop.Properties.Settings>
      <setting name="PalletSolutionsPath" serializeAs="String">
        <value>C:\Program Files (x86)\treeDiM\PLMPack\StackBuilder\PalletSolutionsDB\</value>
      </setting>
...
</treeDiM.StackBuilder.Desktop.Properties.Settings>
</applicationSettings>
</configuration>
```

1. Could you select checkbox "Tools>Parameters>Debugging>Display logging console" and run the software?
Is there any message in the logging console?

2. Also, is the PC connected to the internet and accessible via teamviewer?
Regards,

**Comment by xHuubx** [comment]
0.) Yes this points out to "C:\Program Files (x86)\treeDiM\PLMPack\StackBuilder\PalletSolutionsDB\"
1.) okay when I turned on the debug mode and started SB, I saw a error that indicated that I had not got the right privilages to open de PSDB.

If had this problem before if I install it on a PC I have to give full acces to the file, isn't there a other way to copy the PSDB with the right access to it ?

Thx

**Comment by fgasnier71** [comment]
Version 3 should have online database and accessible by using the same account.
There will no further development on version 2.
Regards,

**Comment by xHuubx** [comment]
Okay great thx! Any idea when version 3 will come out ?

**Comment by fgasnier71** [comment]
Could say it is nearly ready as there is only box/case/pallet analysis and case/pallet optimisation to rewrite but it has been a lot of work (over 1 year).
Would expect it in 3/4 month but not sure.

- will work very differently and you will need to rebuild all the database as compatibility will not be assured.
- will allow editing of stacks (case and pallet) layer by layer,
- will allow nesting analyses,
Regards,
