### ISSUE TITLE
casesDB

### ISSUE THREAD

**Issue by gpacker** [treeDiM/StackBuilder#70]
How to add more cases to the database, to do the box,case,pallet optimization?

**Comment by gpacker** [comment]
IS not working.
I would like to add a new type ob box here
![image](https://cloud.githubusercontent.com/assets/25351178/22330127/bd9df974-e3ab-11e6-9f05-2b111a80a209.png)
 Thanks a lot!

**Comment by gpacker** [comment]
Cheers!

**Comment by fgasnier71** [comment]
Did you succeed to send a palletization solution to the database using the "Send to database" in tree context menu of solution node?

**Comment by gpacker** [comment]
Yes, everything is working now!
Thanks
