### ISSUE TITLE
Portuguese

### ISSUE THREAD

**Issue by gpacker** [treeDiM/StackBuilder#71]
Any possibility to have the templates in portuguese? 
Had some trouble to customize the templates, any tips that help me to customize the templates are welcome!

**Comment by fgasnier71** [comment]
Report strings are in the xml files next to report templates.
There is no portugese resources in the software and it will set itself to English by default.
Workaround : You can set an other language in the settings (e.g. Spanish) and then you need to edit file ESP.xml next to the report template, and translate all the inside strings to portuguese.
