### ISSUE TITLE
Failed to choose xmlAnalysis.allowedBoxPositions

### ISSUE THREAD

**Issue by muxuezi** [treeDiM/StackBuilder#75]
HELP! I'd like to add control with the allowed ortho axes(xmlAnalysis.allowedBoxPositions), we can choose XP, YP, ZP axis, similar to allowed patterns(allowedLayerPatterns), codes as follow:

// allowed ortho axes
// Add control with the allowed ortho axes, we can choose XP, YP, ZP axis
// similar to allowed patterns(allowedLayerPatterns). 

caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_X_N, false);
caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_X_P, false);
caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_Y_N, false);
caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_Y_P, false);
caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_Z_N, false);
caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_Z_P, false);

foreach (positionName ppName in xmlAnalysis.allowedBoxPositions)
{
    switch (ppName)
    {
        case positionName.XP: caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_X_P, true); break;
        case positionName.YP: caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_Y_P, true); break;
        case positionName.ZP: caseConstraintSet.SetAllowedOrthoAxis(HalfAxis.HAxis.AXIS_Z_P, true); break;
        default: break;
    }
}

**Comment by fgasnier71** [comment]
Are you working with the project treeDiM.StackBuilder.XmlFileProcessor?
As you may have noticed StackBuilder is undergoing important modifications to get to a working 3.0 version and this part might not be working anymore.
Did you get anything working with the version you compiled?

**Comment by muxuezi** [comment]
Sorry, I wasn't. I commit two PR, but they are bugs.
