### ISSUE TITLE
Problems with activation

### ISSUE THREAD

**Issue by MarcinRumia** [treeDiM/StackBuilder#77]
I have installed both PLM Pack and stack  builder on Windows 8 machine without any issues. Received activation codes on my email and managed to test the software. Later on I have tried installing same software on Windows 7 machine and got to the activation window stage - user name was already chosen, typed in my email address and organisation name but the next button is still greyed out. To troubleshoot the problem I uninstalled the software on Windows 8 and tried to install it again thinking I must have done something else during installation, but now I am getting the same issue. Cannot send a 'request' for activation codes. What am I doing wrong?
![capture](https://cloud.githubusercontent.com/assets/26301583/23749920/d46b9284-04ca-11e7-9288-f02cb97b6c34.PNG)

**Comment by kDipak** [comment]
Hello

As far as i am aware you can reuse the same key on multiple installations.

Met vriendelijk groet,

Dipak Kumar.

2017-03-09 13:18 GMT+01:00 MarcinRumia <notifications@github.com>:

**Comment by kDipak** [comment]
Hello

As far as i am aware you can reuse the same key on multiple installations.

just tried it and it let me click next

![image](https://cloud.githubusercontent.com/assets/10881222/23751270/da6735b6-04d0-11e7-8ca9-15c18340f4eb.png)


Met vriendelijk groet,

Dipak Kumar.

**Comment by fgasnier71** [comment]
You should have sent an email at the following address: autokey@treedim.com
The autoresponder then sends you an email back with your key, that you copy in the field.

Anyway, the installation key for StackBuilder 2 is: FX15VR70ZH07
