### ISSUE TITLE
Not able to Save/Add Analysys to database

### ISSUE THREAD

**Issue by MarcinRumia** [treeDiM/StackBuilder#78]
First thing first, thank you all for helping me out with installation problems I had. It's all good now. I am digging into how the software actually works. I went through the manual, which showed how to add elements (boxes, cases etc.) After doing the simulation/analysys I wanted to save it so I could use it in further steps doing further simulations (like filling the truck with the load). After following the manual, I was suppose to click on the yellow light bulb and few options are missing as shown on the screenshot. 

Many thanks for your help

![missing options](https://cloud.githubusercontent.com/assets/26301583/23940672/27d0d98a-0966-11e7-843a-e4742e4f5ea7.jpg)

**Comment by MarcinRumia** [comment]
Sorted. I was to quick with analysys. I watched a tutorial on you tube and it helped me out, answering above question and solving the mystery.

Best regrads

**Comment by fgasnier71** [comment]
Using the loaded case as an input for pallet analysis is not possible in version 2. However, it is something that is available in version 3 arriving in the next months.
As a workaround, you can create a case/pallet analysis with a similar case to which you have applied the weight of the loaded case.

**Comment by MarcinRumia** [comment]
Thank you, its great to see that the software is being constantly developed.
