### ISSUE TITLE
How to Add New Record to Existing Data Base

### ISSUE THREAD

**Issue by MarcinRumia** [treeDiM/StackBuilder#79]
I am trying to learn all the ins and outs of the Stackbuilder. At the moment I would like to add new records to the database. Looking at the software at first I thought we can import the data base from excel so I have prepared an excel spreadsheet and formatted it the way the Sample file in Sample Folder has been created. I have changed the default path to lead to the new excel file but nothing has changed. I have also dug to the xml file showing all the default cases (as per screenshot attached). Going through all the files installed with the program I found an xml file alongside native stack builder format files showing all Galia cases. How to add new cases to the program so I can use them in analysis?
![how to have new cases](https://cloud.githubusercontent.com/assets/26301583/23996557/1d1b4f50-0a4e-11e7-908d-d0e7fbce0dcf.png)
![my excel sheet](https://cloud.githubusercontent.com/assets/26301583/23996559/1f2ef2f6-0a4e-11e7-9cfd-2d61762bc2c3.jpeg)
![galia cases](https://cloud.githubusercontent.com/assets/26301583/23996562/21e7fa1a-0a4e-11e7-86e8-59b85a05a983.jpeg)
![xml index](https://cloud.githubusercontent.com/assets/26301583/23996565/23b6218c-0a4e-11e7-9219-bb882657c08c.jpeg)

Thank you all for help

**Comment by fgasnier71** [comment]
You need to:
- build a new case/pallet analysis with the case you want to add,
- select a solution,
- in the tree, right-click the solution added and select something that says "Add to database",
You should then see the case/solution added and ready to be used in you next box/case/pallet analysis.
Regards,
