### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by ahmedwajih** [treeDiM/StackBuilder#80]
which version of visual studio to use to get a work compilation ?
Im using vs 2015 but I have error in compilation*
uncompatible version
also pb in bootstrap ans ExcelDataReader

**Comment by fgasnier71** [comment]
We are currently using VS2013.
Stackbuilder is undergoing heavy modifications and I would recommend that you compile earlier versions.
ExcelDataReader can be reloaded using NuGet...

**Comment by ahmedwajih** [comment]
Dear fgasnier71,
thank you for your kind response,
After several attempts of compilations, I can not execute the code. (many errors)
Can we get a pre intstalled VM  -virtualbox with stackbuilder code source .
regards

**Comment by fgasnier71** [comment]
* Please, do send a copy or excerpt of compilation output with some errors that you get.
* Not sure about the kind VM that you would like to get. Can you explain?
Regards,

**Comment by ahmedwajih** [comment]
well noted;
a virtual machine  on virtualbox which ionclude (windows VM + visual studio + source code )
