### ISSUE TITLE
Importer de la Database

### ISSUE THREAD

**Issue by anobre** [treeDiM/StackBuilder#83]
Lorsque l'on importe de la Database:
- fermer la boite de dialogue de la database après avoir appuyer sur le bouton [Importer]
- Empêcher d'importer un modèle avec le même nom
![image](https://cloud.githubusercontent.com/assets/5347239/25535011/fad09f36-2c35-11e7-9c50-1589f1a69c6e.png)

**Comment by fgasnier71** [comment]
@anobre Attention, je pense qu'il faut laisser à l'utilisateur la possibilité d'importer plusieurs items avant de fermer la boîte de dialogue.
