### ISSUE TITLE
Bundle/pallet Bundle/case analysis

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#86]
Ajouter l' analyse Bundle/pallet ![image](https://cloud.githubusercontent.com/assets/5374935/25664349/a8024e2e-301a-11e7-88be-09928199add4.png) sous le bouton pallet analysis
Ajouter l' analyse Bundle/case ![image](https://cloud.githubusercontent.com/assets/5374935/25664369/b6f09314-301a-11e7-956c-decc39ca1063.png) sous le bouton case analysis
Ajouter l' analyse Pack/case ![image](https://cloud.githubusercontent.com/assets/5374935/25664587/5f831812-301b-11e7-80cf-38f8dd86714d.png) sous le bouton pallet analysis

**Comment by fgasnier71** [comment]
A priori, Bundle se comporte comme une caisse ou un étui.
On utilise donc une analyse caisse/palette ou une analyse étui/palette.

**Comment by pbuffet** [comment]
Oui mais c'est pas clair comme ça. Même si cela utilise la même fonction, pour que l'utilisateur comprenne bien il faudrait mieux l'afficher séparément.

**Comment by pbuffet** [comment]
Si ça coûte rien , ça rend l'utilisation plus évidente

**Comment by fgasnier71** [comment]
Ca parait tellement bizarre de faire pointer deux boutons vers une seule fonction.

**Comment by pbuffet** [comment]
je comprend, mais c'est tellement mieux quand  un utilisateur a compris tout seul comment on fait. 
Mais de toute façon même si c'est la même fonction, l'une propose les caisses dans la liste et l'autre les liasses nan?

**Comment by fgasnier71** [comment]
Non, ça ne fonctionne plus comme ça. Dans le combo, on trouve une liste avec les boîtes/les caisses/les liasses/les packs/les analyses de caisses.

**Comment by pbuffet** [comment]
on ne peut pas filtrer le contenu du combo pour correspondre à l'utilisation souhaité?

**Comment by fgasnier71** [comment]
Non! On choisit un des items. On fait une analyse palette avec tout ce qu'on peut mettre sur une palette.
