### ISSUE TITLE
Bouton User

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#87]
Ajouter un bouton USER ![user](https://cloud.githubusercontent.com/assets/5374935/25697112/f8ed1202-30b9-11e7-8d3d-6a97093ff57c.png), qui déroule une liste de fonction:

Même fonction que dans PackLib:
![image](https://cloud.githubusercontent.com/assets/5374935/25697174/388a9a38-30ba-11e7-89a1-62aefc5e2bd8.png)

**Comment by fgasnier71** [comment]
L'icône n'est pas la même (couleur). Est-ce voulu?

**Comment by pbuffet** [comment]
oui couleur stackbuilder
