### ISSUE TITLE
Ne parvient pas à générer de rapport de palettisation 

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#89]
StackBuilder ne parvient pas à générer de rapport de palettisation (html ou .doc)

html: rien ne se passe
.doc : ne crée que le dossier images

**Comment by fgasnier71** [comment]
Ca fonctionne pour moi.
Peux-tu m'envoyer activer le mode debug(Settings\Debugging\Show log console) et m'envoyer les exceptions qui apparaissent?
Sinon, peux tu vérifier si le ReportTemplate dans l'onglet reporting des settings pointe bien vers un fichier "ReportTemplate.xsl" existant?

**Comment by pbuffet** [comment]
J'ai (re)pointé sur le template, maintenant cela fonctionne correctement.
Pas d'erreur dans la console.

Hum... tant mieux

**Comment by fgasnier71** [comment]
Qui y avait-il dans le champ report template?

**Comment by pbuffet** [comment]
Le bon reportTemplate.xsl , je retesterai sur une autre machine après la toute première installation de StackBuilder.

**Comment by fgasnier71** [comment]
Je pense avoir découvert la raison du problème. Le chemin par défaut n'est calculé que lorsqu'on ouvre l'onglet.
