### ISSUE TITLE
Can you combine different box sizes on one pallet?

### ISSUE THREAD

**Issue by YosefMK** [treeDiM/StackBuilder#91]
This would be a great option for shipping out mixed orders!

**Comment by anobre** [comment]
Hello Yosef,

Thanks for your message.

Our software is mainly designed for the packaging designers (CAD software users)  to optimize an packaging system (primary, secondary (transport) packaging, palettization, truck load).

StackBuilder is not for the complete optimization of logistics. 

 

Cordialement, 

  _____  

Alain Nobre   

 <http://www.treedim.com/> 

treeDiM | 1 rue des frères LUMIERE | 
F-92500 RUEIL-MALMAISON  - FRANCE 
Phone: +33 (0)1 41 42 19 36 
GSM : +33 (0)6 70 67 49 33  (WhatsApp)

skype : alain.nobre
email :  <mailto:anobre@treedim.com> anobre@treedim.com 

web :   <http://www.treedim.com/> http://www.treedim.com

 

 

De : YosefMK [mailto:notifications@github.com] 
Envoyé : mercredi 14 juin 2017 21:41
À : treeDiM/StackBuilder <StackBuilder@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [treeDiM/StackBuilder] Can you combine different box sizes on one pallet? (#91)

 

This would be a great option for shipping out mixed orders!

**Comment by YosefMK** [comment]
Thanks!
But you still have a great program!

PS - would you have a recommendation of a program that would have this kind
of function?

**Comment by fgasnier71** [comment]
Cape pack:
https://www.esko.com/fr/products/cape-pack
Puzzle:
http://www.iml.fraunhofer.de/de/abteilungen/b1/software_engineering/puzzle.html
