### ISSUE TITLE
Liste des palettes

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/StackBuilder#92]
![image](https://user-images.githubusercontent.com/5374935/27795798-c0667202-6007-11e7-9722-bf18f3ef2041.png)

Ajouter la palette EUR 1200*800 dans la liste. 
Placer EUR et EUR2 en haut de la liste pour utiliser EUR comme palette par défaut

(issue 61 déplacée depuis le projet PackLib)

**Comment by fgasnier71** [comment]
Les palettes apparaîtront désormais dans l'ordre alphabétique.
Sinon, ce sont celles définies par l'utilisateur dans la base de données.
Si l'utilisateur créé des palettes dont le nom précède alphabétiquement EUR, celles-ci se trouveront bien évidemment avant les palettes EUR...
J'ai supprimé les palettes CHEP dans le groupe treeDiM si bien qu'un nouvel utilisateur ne les auras pas lorsqu'il créera un compte. Cependant, je ne peux rien faire pour les utilisateurs existants qui devront les supprimer eux-mêmes.
