### ISSUE TITLE
Case/box analysis freeze and offline mode

### ISSUE THREAD

**Issue by yeutinh** [treeDiM/StackBuilder#93]
Dear team,

I tried the new version of Stackbuilder when checking out Packlib.

This version is much better in regard to options and feature, however slightly slower on the processing, especially on 64b Win.

Checked case/box analysis on 3 version of windows and all freezes, at the point of selecting a layout and proceed to analysis. Taskmanager report app is running but get nowhere after 10 minutes.

Also, like the new Packlib, can't run in offline mode. Is there any chance it will be in future update ?

Thanks for the great work team

Regards

Luan

**Comment by fgasnier71** [comment]
Hello Luan,
Thanks for sharing about this bug in box/case analysis.
There is a problem however as I failed to reproduce it. Box/case analysis seems to work fine for me.
Could you detail the steps that lead to the infinite loop? (i.e. dimensions of box and case, the button used for analysis creation...)

**Comment by yeutinh** [comment]
Hi Francois,

Long time no talk. I was hoping you are doing well ! Being a new technology
minister for the government perhaps ?

I installed the new version of the StackBuilder on 2 laptops and 1 desktop.
Logging in was fine.

I create a box, then a case.

Then I proceed to use the box/case analysis just to see the various
configuration that the new version can bring up, checked with "best option
... " at the bottom. The loop started when I click NEXT.

Then it stuck there ... not sure what happened, so usually after 5 minutes
I kill the process. I did leave it on for 30 minutes once to see if it is a
processing issue, no difference. I did also try to see if an error window
pop under somewhere that need clicking, but couldn't find anything.

Anyway, the good thing is the older version co-exist without problem. I
feel the biggest bug is that when I have to disconnect the internet, the
new version of both stackbuilder and packlib stopworking, and that is
really annoying.

My company installed CAPE for my workstation with all the modules, costing
$20k and the report it spit out is very rudimentary, seemed to be a waste
of money.

Looking forward to hear from you ...

Best Regards

Luan







On Thu, Jul 20, 2017 at 12:10 AM, François Gasnier <notifications@github.com

**Comment by fgasnier71** [comment]
Will implement an offline mode, that you will be able to set from settings.
You will however still need to connect a first time.

**Comment by fgasnier71** [comment]
* From version 3.0.0.46, you can allow an offline mode.
* Goto Settings>Debugging>Allow disconnected usage
* You should now be able to restart the application and work offline.

**Comment by yeutinh** [comment]
Many thanks Francois.
